services:

  backend:

    build:
      context: ./backend

    container_name: devinsight-backend


    ports:
      - "8000:8000"


    env_file:
      - ./backend/.env


    volumes:
      - ./backend:/app